services:
  api:
    build: .
    container_name: couture_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:16-alpine
    container_name: couture_postgres
    environment:
      POSTGRES_DB: couture_catalog
      POSTGRES_USER: couture
      POSTGRES_PASSWORD: couture
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U couture -d couture_catalog"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

